export const LISTING_REGISTER_REQUEST = 'LISTING_REGISTER_REQUEST'
export const LISTING_REGISTER_SUCCESS = 'LISTING_REGISTER_SUCCESS'
export const LISTING_REGISTER_FAIL = 'LISTING_REGISTER_FAIL'

export const LISTING_LIST_REQUEST = 'LISTING_LIST_REQUEST'
export const LISTING_LIST_SUCCESS = 'LISTING_LIST_SUCCESS'
export const LISTING_LIST_FAIL = 'LISTING_LIST_FAIL'
export const LISTING_LIST_RESET = 'LISTING_LIST_RESET'
