export const LISTING_REGISTER_REQUEST = 'LISTING_REGISTER_REQUEST'
export const LISTING_REGISTER_SUCCESS = 'LISTING_REGISTER_SUCCESS'
export const LISTING_REGISTER_FAIL = 'LISTING_REGISTER_FAIL'

export const LISTING_LIST_REQUEST = 'LISTING_LIST_REQUEST'
export const LISTING_LIST_SUCCESS = 'LISTING_LIST_SUCCESS'
export const LISTING_LIST_FAIL = 'LISTING_LIST_FAIL'
export const LISTING_LIST_RESET = 'LISTING_LIST_RESET'

export const LISTING_DETAILS_REQUEST = 'LISTING_DETAILS_REQUEST'
export const LISTING_DETAILS_SUCCESS = 'LISTING_DETAILS_SUCCESS'
export const LISTING_DETAILS_FAIL = 'LISTING_DETAILS_FAIL'
export const LISTING_DETAILS_RESET = 'LISTING_DETAILS_RESET'

export const LISTING_UPDATE_PROFILE_REQUEST = 'LISTING_UPDATE_PROFILE_REQUEST'
export const LISTING_UPDATE_PROFILE_SUCCESS = 'LISTING_UPDATE_PROFILE_SUCCESS'
export const LISTING_UPDATE_PROFILE_FAIL = 'LISTING_UPDATE_PROFILE_FAIL'
export const LISTING_UPDATE_PROFILE_RESET = 'LISTING_UPDATE_PROFILE_RESET'
