export const VENDOR_REGISTER_REQUEST = 'VENDOR_REGISTER_REQUEST'
export const VENDOR_REGISTER_SUCCESS = 'VENDOR_REGISTER_SUCCESS'
export const VENDOR_REGISTER_FAIL = 'VENDOR_REGISTER_FAIL'

export const VENDOR_DETAILS_REQUEST = 'VENDOR_DETAILS_REQUEST'
export const VENDOR_DETAILS_SUCCESS = 'VENDOR_DETAILS_SUCCESS'
export const VENDOR_DETAILS_FAIL = 'VENDOR_DETAILS_FAIL'
export const VENDOR_DETAILS_RESET = 'VENDOR_DETAILS_RESET'

export const VENDOR_UPDATE_PROFILE_REQUEST = 'VENDOR_UPDATE_PROFILE_REQUEST'
export const VENDOR_UPDATE_PROFILE_SUCCESS = 'VENDOR_UPDATE_PROFILE_SUCCESS'
export const VENDOR_UPDATE_PROFILE_FAIL = 'VENDOR_UPDATE_PROFILE_FAIL'
export const VENDOR_UPDATE_PROFILE_RESET = 'VENDOR_UPDATE_PROFILE_RESET'

export const VENDOR_LIST_REQUEST = 'VENDOR_LIST_REQUEST'
export const VENDOR_LIST_SUCCESS = 'VENDOR_LIST_SUCCESS'
export const VENDOR_LIST_FAIL = 'VENDOR_LIST_FAIL'
export const VENDOR_LIST_RESET = 'VENDOR_LIST_RESET'

export const VENDOR_ALL_LIST_REQUEST = 'VENDOR_ALL_LIST_REQUEST'
export const VENDOR_ALL_LIST_SUCCESS = 'VENDOR_ALL_LIST_SUCCESS'
export const VENDOR_ALL_LIST_FAIL = 'VENDOR_ALL_LIST_FAIL'

